# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui',
# licensing of 'calc.ui' applies.
#
# Created: Sat Oct 19 21:27:01 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.consol = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.consol.setFont(font)
        self.consol.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.consol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.consol.setReadOnly(True)
        self.consol.setPlaceholderText("")
        self.consol.setObjectName("consol")
        self.gridLayout_2.addWidget(self.consol, 0, 0, 1, 1)
        self.consol2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(15)
        font.setWeight(50)
        font.setBold(False)
        self.consol2.setFont(font)
        self.consol2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.consol2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.consol2.setReadOnly(True)
        self.consol2.setPlaceholderText("")
        self.consol2.setObjectName("consol2")
        self.gridLayout_2.addWidget(self.consol2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.degree = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.degree.sizePolicy().hasHeightForWidth())
        self.degree.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.degree.setFont(font)
        self.degree.setObjectName("degree")
        self.gridLayout.addWidget(self.degree, 0, 2, 1, 1)
        self.six = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.six.sizePolicy().hasHeightForWidth())
        self.six.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.six.setFont(font)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 1, 1, 1, 1)
        self.one = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one.sizePolicy().hasHeightForWidth())
        self.one.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.one.setFont(font)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 3, 0, 1, 1)
        self.multiplication = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiplication.sizePolicy().hasHeightForWidth())
        self.multiplication.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.multiplication.setFont(font)
        self.multiplication.setObjectName("multiplication")
        self.gridLayout.addWidget(self.multiplication, 0, 3, 1, 1)
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eight.sizePolicy().hasHeightForWidth())
        self.eight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.eight.setFont(font)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 2, 2, 1, 1)
        self.three = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.three.sizePolicy().hasHeightForWidth())
        self.three.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.three.setFont(font)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 1, 0, 1, 1)
        self.five = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.five.sizePolicy().hasHeightForWidth())
        self.five.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.five.setFont(font)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 2, 1, 1, 1)
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plus.sizePolicy().hasHeightForWidth())
        self.plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 0, 0, 1, 1)
        self.four = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.four.sizePolicy().hasHeightForWidth())
        self.four.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.four.setFont(font)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 3, 1, 1, 1)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 3, 3, 2, 1)
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero.sizePolicy().hasHeightForWidth())
        self.zero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.zero.setFont(font)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 4, 0, 1, 3)
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minus.sizePolicy().hasHeightForWidth())
        self.minus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 0, 1, 1, 1)
        self.two = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two.sizePolicy().hasHeightForWidth())
        self.two.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.two.setFont(font)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 2, 0, 1, 1)
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nine.sizePolicy().hasHeightForWidth())
        self.nine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.nine.setFont(font)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 1, 2, 1, 1)
        self.equally = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equally.sizePolicy().hasHeightForWidth())
        self.equally.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.equally.setFont(font)
        self.equally.setObjectName("equally")
        self.gridLayout.addWidget(self.equally, 1, 3, 2, 1)
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seven.sizePolicy().hasHeightForWidth())
        self.seven.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.seven.setFont(font)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 26))
        self.menubar.setTabletTracking(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Калькулятор", None, -1))
        self.consol.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.consol2.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.degree.setText(QtWidgets.QApplication.translate("MainWindow", "/", None, -1))
        self.six.setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.one.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.multiplication.setText(QtWidgets.QApplication.translate("MainWindow", "*", None, -1))
        self.eight.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.three.setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.five.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.plus.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.four.setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.clear.setText(QtWidgets.QApplication.translate("MainWindow", "С", None, -1))
        self.zero.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.minus.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.two.setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.nine.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.equally.setText(QtWidgets.QApplication.translate("MainWindow", "=", None, -1))
        self.seven.setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))

